In [105]:
import numpy as np
import pandas as pd

After importing all the necessary libraries, I read the 'movies.csv' file showing just the head.

In [106]:
# read movies csv file
df = pd.read_csv('movies.csv')
df.head()

MOVIES         YEAR  \
0                        Blood Red Sky       (2021)   
1  Masters of the Universe: Revelation     (2021– )   
2                     The Walking Dead  (2010–2022)   
3                       Rick and Morty     (2013– )   
4                      Army of Thieves       (2021)   

                                        GENRE  RATING  \
0      \nAction, Horror, Thriller                 6.1   
1  \nAnimation, Action, Adventure                 5.0   
2       \nDrama, Horror, Thriller                 8.2   
3  \nAnimation, Adventure, Comedy                 9.2   
4         \nAction, Crime, Horror                 NaN   

                                            ONE-LINE  \
0  \nA woman with a mysterious illness is forced ...   
1  \nThe war for Eternia begins again in what may...   
2  \nSheriff Deputy Rick Grimes wakes up from a c...   
3  \nAn animated series that follows the exploits...   
4  \nA prequel, set before the events of Army of ...   

                                               STARS    VOTES  RunTime Gross  
0  \n    Director:\nPeter Thorwarth\n| \n    Star...   21,062    121.0   NaN  
1  \n            \n    Stars:\nChris Wood, \nSara...   17,870     25.0   NaN  
2  \n            \n    Stars:\nAndrew Lincoln, \n...  885,805     44.0   NaN  
3  \n            \n    Stars:\nJustin Roiland, \n...  414,849     23.0   NaN  
4  \n    Director:\nMatthias Schweighöfer\n| \n  ...      NaN      NaN   NaN

Here I tried to check and confirm all the datatypes for each column

In [107]:
# checking the datatype of all the columns
df.dtypes

MOVIES       object
YEAR         object
GENRE        object
RATING      float64
ONE-LINE     object
STARS        object
VOTES        object
RunTime     float64
Gross        object
dtype: object

Here I checked for missing values. Then I found that there are some missing values in columns like YEAR, GENRE, RATING, VOTES, RunTime Aand Gross. 

In [152]:
# checking for missing values
df.isnull().any()

MOVIES      False
YEAR        False
GENRE       False
RATING      False
ONE-LINE    False
STARS       False
VOTES       False
RunTime     False
Gross       False
dtype: bool

Here I replaced the missing values with str '2021'

In [154]:
# replacing null values in YEAR Column
df['YEAR'].fillna('2021', inplace=True)
df.head()

MOVIES         YEAR  \
0                        Blood Red Sky       (2021)   
1  Masters of the Universe: Revelation     (2021– )   
2                     The Walking Dead  (2010–2022)   
3                       Rick and Morty     (2013– )   
4                      Army of Thieves       (2021)   

                                        GENRE    RATING  \
0      \nAction, Horror, Thriller              6.100000   
1  \nAnimation, Action, Adventure              5.000000   
2       \nDrama, Horror, Thriller              8.200000   
3  \nAnimation, Adventure, Comedy              9.200000   
4         \nAction, Crime, Horror              6.921176   

                                            ONE-LINE  \
0  \nA woman with a mysterious illness is forced ...   
1  \nThe war for Eternia begins again in what may...   
2  \nSheriff Deputy Rick Grimes wakes up from a c...   
3  \nAn animated series that follows the exploits...   
4  \nA prequel, set before the events of Army of ...   

                                               STARS    VOTES     RunTime  \
0  \n    Director:\nPeter Thorwarth\n| \n    Star...   21,062  121.000000   
1  \n            \n    Stars:\nChris Wood, \nSara...   17,870   25.000000   
2  \n            \n    Stars:\nAndrew Lincoln, \n...  885,805   44.000000   
3  \n            \n    Stars:\nJustin Roiland, \n...  414,849   23.000000   
4  \n    Director:\nMatthias Schweighöfer\n| \n  ...  414,849   68.688539   

     Gross  
0  150.70M  
1  150.70M  
2  150.70M  
3  150.70M  
4  150.70M

At the GENRE column I noticed that the most common GENRE is '\nAnimation, Action, Adventure' and it's str, so I replaced the null values there with it.

In [118]:
# filling the GENRE column
df['GENRE'].fillna('\nAnimation, Action, Adventure', inplace=True)
df.head()

MOVIES         YEAR  \
0                        Blood Red Sky       (2021)   
1  Masters of the Universe: Revelation     (2021– )   
2                     The Walking Dead  (2010–2022)   
3                       Rick and Morty     (2013– )   
4                      Army of Thieves       (2021)   

                                        GENRE    RATING  \
0      \nAction, Horror, Thriller              6.100000   
1  \nAnimation, Action, Adventure              5.000000   
2       \nDrama, Horror, Thriller              8.200000   
3  \nAnimation, Adventure, Comedy              9.200000   
4         \nAction, Crime, Horror              6.921176   

                                            ONE-LINE  \
0  \nA woman with a mysterious illness is forced ...   
1  \nThe war for Eternia begins again in what may...   
2  \nSheriff Deputy Rick Grimes wakes up from a c...   
3  \nAn animated series that follows the exploits...   
4  \nA prequel, set before the events of Army of ...   

                                               STARS    VOTES     RunTime  \
0  \n    Director:\nPeter Thorwarth\n| \n    Star...   21,062  121.000000   
1  \n            \n    Stars:\nChris Wood, \nSara...   17,870   25.000000   
2  \n            \n    Stars:\nAndrew Lincoln, \n...  885,805   44.000000   
3  \n            \n    Stars:\nJustin Roiland, \n...  414,849   23.000000   
4  \n    Director:\nMatthias Schweighöfer\n| \n  ...  414,849   68.688539   

     Gross  
0  150.70M  
1  150.70M  
2  150.70M  
3  150.70M  
4  150.70M

RATINg has so many missong values, but then I tried replacing them with the mean of the available values since its datatype is float64.

In [117]:
# filling the RATING column

x = df['RATING'].mean()
df['RATING'].fillna(x, inplace=True)
df.tail()

MOVIES      YEAR  \
9994      The Imperfects  (2021– )   
9995              Arcane  (2021– )   
9996   Heart of Invictus  (2022– )   
9997      The Imperfects  (2021– )   
9998      The Imperfects  (2021– )   

                                           GENRE    RATING        ONE-LINE  \
9994     \nAdventure, Drama, Fantasy              6.921176  \nAdd a Plot\n   
9995  \nAnimation, Action, Adventure              6.921176  \nAdd a Plot\n   
9996            \nDocumentary, Sport              6.921176  \nAdd a Plot\n   
9997     \nAdventure, Drama, Fantasy              6.921176  \nAdd a Plot\n   
9998     \nAdventure, Drama, Fantasy              6.921176  \nAdd a Plot\n   

                                                  STARS    VOTES    RunTime  \
9994  \n            \n    Stars:\nMorgan Taylor Camp...  414,849  68.688539   
9995                                                 \n  414,849  68.688539   
9996  \n    Director:\nOrlando von Einsiedel\n| \n  ...  414,849  68.688539   
9997  \n    Director:\nJovanka Vuckovic\n| \n    Sta...  414,849  68.688539   
9998  \n    Director:\nJovanka Vuckovic\n| \n    Sta...  414,849  68.688539   

        Gross  
9994  150.70M  
9995  150.70M  
9996  150.70M  
9997  150.70M  
9998  150.70M

The VOTES column has many missing values as well but then it's a str datatype, so using mean without converting the datatype will not work so I checked for the most commoon value in the column ('414,849') and used it to replace the missing ones.

In [115]:
# filling the VOTES column

df['VOTES'].fillna('414,849', inplace=True)
df.head()

MOVIES         YEAR  \
0                        Blood Red Sky       (2021)   
1  Masters of the Universe: Revelation     (2021– )   
2                     The Walking Dead  (2010–2022)   
3                       Rick and Morty     (2013– )   
4                      Army of Thieves       (2021)   

                                        GENRE    RATING  \
0      \nAction, Horror, Thriller              6.100000   
1  \nAnimation, Action, Adventure              5.000000   
2       \nDrama, Horror, Thriller              8.200000   
3  \nAnimation, Adventure, Comedy              9.200000   
4         \nAction, Crime, Horror              6.921176   

                                            ONE-LINE  \
0  \nA woman with a mysterious illness is forced ...   
1  \nThe war for Eternia begins again in what may...   
2  \nSheriff Deputy Rick Grimes wakes up from a c...   
3  \nAn animated series that follows the exploits...   
4  \nA prequel, set before the events of Army of ...   

                                               STARS    VOTES     RunTime  \
0  \n    Director:\nPeter Thorwarth\n| \n    Star...   21,062  121.000000   
1  \n            \n    Stars:\nChris Wood, \nSara...   17,870   25.000000   
2  \n            \n    Stars:\nAndrew Lincoln, \n...  885,805   44.000000   
3  \n            \n    Stars:\nJustin Roiland, \n...  414,849   23.000000   
4  \n    Director:\nMatthias Schweighöfer\n| \n  ...  414,849   68.688539   

     Gross  
0  150.70M  
1  150.70M  
2  150.70M  
3  150.70M  
4  150.70M

The RunTime datatype is float64 so it was abit easier to check and use the mean of the values to fill the missing values.

In [116]:
# filling NaN values in RunTime column
x = df['RunTime'].mean()
df['RunTime'].fillna(x, inplace=True)
df.head()

MOVIES         YEAR  \
0                        Blood Red Sky       (2021)   
1  Masters of the Universe: Revelation     (2021– )   
2                     The Walking Dead  (2010–2022)   
3                       Rick and Morty     (2013– )   
4                      Army of Thieves       (2021)   

                                        GENRE    RATING  \
0      \nAction, Horror, Thriller              6.100000   
1  \nAnimation, Action, Adventure              5.000000   
2       \nDrama, Horror, Thriller              8.200000   
3  \nAnimation, Adventure, Comedy              9.200000   
4         \nAction, Crime, Horror              6.921176   

                                            ONE-LINE  \
0  \nA woman with a mysterious illness is forced ...   
1  \nThe war for Eternia begins again in what may...   
2  \nSheriff Deputy Rick Grimes wakes up from a c...   
3  \nAn animated series that follows the exploits...   
4  \nA prequel, set before the events of Army of ...   

                                               STARS    VOTES     RunTime  \
0  \n    Director:\nPeter Thorwarth\n| \n    Star...   21,062  121.000000   
1  \n            \n    Stars:\nChris Wood, \nSara...   17,870   25.000000   
2  \n            \n    Stars:\nAndrew Lincoln, \n...  885,805   44.000000   
3  \n            \n    Stars:\nJustin Roiland, \n...  414,849   23.000000   
4  \n    Director:\nMatthias Schweighöfer\n| \n  ...  414,849   68.688539   

     Gross  
0  150.70M  
1  150.70M  
2  150.70M  
3  150.70M  
4  150.70M

Gross column has the highest number of missing values, but then it's a str datatype. I tried converting the datatype to float or int so I can use the mean or mode of the values to fill the missing ones, but then it didn't work for me. So decided to use a avarage number '150.70M' to fill all the missing values.

In [113]:
# filling NaN values in Gross column
df['Gross'].fillna('150.70M', inplace=True)
df.head()

MOVIES         YEAR  \
0                        Blood Red Sky       (2021)   
1  Masters of the Universe: Revelation     (2021– )   
2                     The Walking Dead  (2010–2022)   
3                       Rick and Morty     (2013– )   
4                      Army of Thieves       (2021)   

                                        GENRE    RATING  \
0      \nAction, Horror, Thriller              6.100000   
1  \nAnimation, Action, Adventure              5.000000   
2       \nDrama, Horror, Thriller              8.200000   
3  \nAnimation, Adventure, Comedy              9.200000   
4         \nAction, Crime, Horror              6.921176   

                                            ONE-LINE  \
0  \nA woman with a mysterious illness is forced ...   
1  \nThe war for Eternia begins again in what may...   
2  \nSheriff Deputy Rick Grimes wakes up from a c...   
3  \nAn animated series that follows the exploits...   
4  \nA prequel, set before the events of Army of ...   

                                               STARS    VOTES     RunTime  \
0  \n    Director:\nPeter Thorwarth\n| \n    Star...   21,062  121.000000   
1  \n            \n    Stars:\nChris Wood, \nSara...   17,870   25.000000   
2  \n            \n    Stars:\nAndrew Lincoln, \n...  885,805   44.000000   
3  \n            \n    Stars:\nJustin Roiland, \n...  414,849   23.000000   
4  \n    Director:\nMatthias Schweighöfer\n| \n  ...  414,849   68.688539   

     Gross  
0  150.70M  
1  150.70M  
2  150.70M  
3  150.70M  
4  150.70M

Here, after filling all the missing values in all the columns, I tried to reconfirm and they all showed false.

In [114]:
# checking if I still have null value in the whole DataFrame. Good, I don't have!
df.isnull().any()

MOVIES      False
YEAR        False
GENRE       False
RATING      False
ONE-LINE    False
STARS       False
VOTES       False
RunTime     False
Gross       False
dtype: bool

The next thing I did was check for deplicates and it shpwed True.

In [140]:
# checking for duplicate row
df.duplicated().any()

True

Then I tried to confirm how many rows where duplicated and I got about 431 rows

In [141]:
# checking for how duplicate row
df.duplicated().sum()

431

Here I just tried to cofirm if all the columns has duplicates so i will know the how to apply the drop_duplicates function.

In [145]:
# showing the duplicates row
df[df.duplicated(['MOVIES'], keep=False)].sort_values(by=['MOVIES']).sum()

C:\Users\STUTERN\AppData\Local\Temp\ipykernel_23216\91571892.py:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df[df.duplicated(['MOVIES'], keep=False)].sort_values(by=['MOVIES']).sum()


MOVIES       13 Reasons Why 13 Reasons Why 13 Reasons Why ...
GENRE       \nDrama, Mystery, Thriller            \nDrama,...
RATING                                           23610.389277
ONE-LINE    \nThe Jensens make the boys take a drug test. ...
STARS       \n    Director:\nBrenda Strong\n| \n    Stars:...
VOTES       1,5071,6941,7141,6192,3121,6401,4201,5971,6351...
RunTime                                         161765.492118
Gross       150.70M150.70M150.70M150.70M150.70M150.70M150....
dtype: object

Here I dropped all the 431 duplicates, keeping the first row before the duplicates and ignoring the index so the table will still be well arranged.

In [143]:
# dropping duplicate rows
df.drop_duplicates(subset=None, keep='first', inplace=True, ignore_index=False)
df.head()

MOVIES         YEAR  \
0                        Blood Red Sky       (2021)   
1  Masters of the Universe: Revelation     (2021– )   
2                     The Walking Dead  (2010–2022)   
3                       Rick and Morty     (2013– )   
4                      Army of Thieves       (2021)   

                                        GENRE    RATING  \
0      \nAction, Horror, Thriller              6.100000   
1  \nAnimation, Action, Adventure              5.000000   
2       \nDrama, Horror, Thriller              8.200000   
3  \nAnimation, Adventure, Comedy              9.200000   
4         \nAction, Crime, Horror              6.921176   

                                            ONE-LINE  \
0  \nA woman with a mysterious illness is forced ...   
1  \nThe war for Eternia begins again in what may...   
2  \nSheriff Deputy Rick Grimes wakes up from a c...   
3  \nAn animated series that follows the exploits...   
4  \nA prequel, set before the events of Army of ...   

                                               STARS    VOTES     RunTime  \
0  \n    Director:\nPeter Thorwarth\n| \n    Star...   21,062  121.000000   
1  \n            \n    Stars:\nChris Wood, \nSara...   17,870   25.000000   
2  \n            \n    Stars:\nAndrew Lincoln, \n...  885,805   44.000000   
3  \n            \n    Stars:\nJustin Roiland, \n...  414,849   23.000000   
4  \n    Director:\nMatthias Schweighöfer\n| \n  ...  414,849   68.688539   

     Gross  
0  150.70M  
1  150.70M  
2  150.70M  
3  150.70M  
4  150.70M

I just reconfirmed if I still have duplicates and it turned False.

In [146]:
# confirming if there are still dupliacte rows
df.duplicated().any()

False

Ms Chinenye, I tried using google colab but then it was telling me file not in my directory. I watched some videos to fix it but then it was taking much of my time and I needed to get this done within some time frame. 
So I decided to use Jupiter Note book. I know it wasn't your instruction but please pardon me for that.